---
- hosts: all
  become: true
  gather_facts: false
  vars_files:
    - "../vault/vault.yml"
  tasks:
    - name: "Installation de mongodb"
      include_tasks: ./tasks/install_mongodb.yml

    - name: "Montage du volume"
      include_tasks: ./tasks/mount_volume.yml

    - name: "Copie des fichiers"
      include_tasks: ./tasks/files_copy.yml

    - name: "Lancement des services systeme"
      include_tasks: ./tasks/system.yml

    - name: "Installation des certificats TLS"
      include_tasks: ./tasks/install_tls.yml

    - name: "Démarrage de mongodb"
      include_tasks: ./tasks/start_mongodb.yml

    - name: "Ajout du membre au replicat set"
      ansible.builtin.shell:
        cmd: "/opt/app/scripts/register_member.sh"
      when: context == "new-member"

    - name: "Configuration du replicat set"
      include_tasks: ./tasks/config_replicat_set.yml
      when: context == "new-cluster"

    - name: "Configuration des utilisateurs"
      include_tasks: ./tasks/create_users.yml
      when: context == "new-cluster" or context == "update"
    
    - name: "Configuration de la sauvegarde de la base de données"
      import_tasks: ./tasks/configure-mongodb-backup.yml
      when: backup_enable | default(false) | bool

    - name: "Percona"
      include_tasks: ./tasks/percona.yml

    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true

  handlers:
    - name: Reload Daemon
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Restart MongoDB
      ansible.builtin.service:
        name: mongod
        state: restarted
        enabled: yes

    - name: Restart THP
      ansible.builtin.service:
        name: disable-transparent-huge-pages
        state: restarted
        enabled: yes

    - name: restart-logrotate
      service:
        name: logrotate
        enabled: true
        state: restarted
