---
- hosts: all
  become: true
  gather_facts: false
  tasks:

    - name: Chargement des variables chiffrées globales
      community.sops.load_vars:
        file: "{{ inventory_dir }}/../env.global.yml"
        expressions: ignore

    - name: Chargement des variables chiffrées de l'environnement {{ env_type }}
      community.sops.load_vars:
        file: "{{ inventory_dir }}/../env.{{ env_type }}.yml"
        expressions: ignore

    - name: "Suppression du noeud"
      ansible.builtin.shell:
        cmd: "/opt/app/scripts/remove_member.sh"

  handlers:
    - name: Restart MongoDB
      ansible.builtin.service:
        name: mongod
        state: restarted
        enabled: yes
