---
- name: "Create role any"
  include_tasks: create_role.yml
  vars:
    role:
      name: "any"
      privileges:
        - resource:
            anyResource: true
          actions: [anyAction]

- name: "Create custom roles"
  include_tasks: create_role.yml
  loop: "{{vault[env_type].roles}}"
  loop_control:
    loop_var: role
  when: "{{vault[env_type].roles | default('') | length > 0 }}"

- name: "Create users"
  include_tasks: create_user.yml
  loop: "{{vault[env_type].users}}"
  loop_control:
    loop_var: user

- name: "Create root user"
  include_tasks: create_user.yml
  vars:
    user:
      name: "root"
      password: "{{vault[env_type].root}}"
      database: "admin"
      roles: "root"

- name: "Create backup user"
  include_tasks: create_user.yml
  vars:
    user:
      name: "backup"
      password: "{{vault[env_type].backup}}"
      database: "admin"
      roles: "any"

- name: "Create pmm user"
  include_tasks: create_user.yml
  vars:
    user:
      name: "pmm"
      password: "{{vault[env_type].pmm}}"
      database: "admin"
      roles: "any"
