---
- name: "Create role any"
  include_tasks: create_role.yml
  vars:
    role:
      name: "any"
      database: "admin"
      privileges:
        - resource:
            anyResource: true
          actions: [anyAction]
      roles: []

- name: "Create custom roles"
  include_tasks: create_role.yml
  loop: "{{roles}}"
  loop_control:
    loop_var: role
  when: "roles | default('') | length > 0"

- name: "Create users"
  include_tasks: create_user.yml
  loop: "{{users}}"
  loop_control:
    loop_var: user

- name: "Create root user"
  include_tasks: create_user.yml
  vars:
    user:
      name: "root"
      password: "{{root}}"
      database: "admin"
      roles:
        - role: "root"
          db: 'admin'

- name: "Create backup user"
  include_tasks: create_user.yml
  vars:
    user:
      name: "backup"
      password: "{{backup}}"
      database: "admin"
      roles:
        - role: "any"
          db: 'admin'

- name: "Create pmm user"
  include_tasks: create_user.yml
  vars:
    user:
      name: "pmm"
      password: "{{pmm}}"
      database: "admin"
      roles:
        - role: "any"
          db: 'admin'
