---
- name: "Generate MongoDB X.509 certificate"
  shell:
    cmd: '/opt/app/scripts/ca.sh renew {{ dns_name }}'

- name: "Create CRON task to renew MongoDB X.509 certificate"
  ansible.builtin.cron:
    name: "mongodb-ca-x509-certificate-renew"
    minute: "0"
    hour: "4"
    job: "bash /opt/app/scripts/ca.sh renew {{ dns_name }} >> /var/log/cron.log 2>&1; /opt/app/tools/monitoring/export-cron-status-prom.sh -c 'MongoDB - Renewal of the private X.509 certificate' -v $?"

