---
- name: Récupération des images docker
  shell:
    chdir: /opt/app
    cmd: "sudo docker compose $(for file in $(ls docker-compose.*.yml); do echo -n \"-f $file \"; done) pull"

- name: Récupération du status de la stack
  shell:
    chdir: /opt/app
    cmd: docker stack ls --format json
  register: stack_status

- name: Lancement de l'application {{env_type}}
  shell:
    chdir: /opt/app
    cmd: "/opt/app/tools/update-stack.sh"
  register: docker_deploy_output

- debug:
    var: docker_deploy_output

- name: Attente du deploiement
  shell:
    chdir: /opt/app
    cmd: "/opt/app/tools/wait-deployment.sh"
  async: 1800
  poll: 10

- name: "Reload du Reverse Proxy"
  shell:
    chdir: /opt/app
    cmd: "sudo /opt/app/tools/reload-proxy.sh"

- name: "Désactivation du mode maintenance"
  shell:
    chdir: /opt/app
    cmd: "sudo /opt/app/tools/maintenance/maintenance-off.sh"

- name: "Verification des certificats SSL"
  shell:
    chdir: /opt/app
    cmd: "sudo /opt/app/tools/ssl/renew-certificate.sh {{dns_name}}"

- name: "Prune Docker"
  shell:
    chdir: /opt/app
    cmd: "sudo docker system prune --all --force"