name: Setup Batch
on:
  workflow_dispatch:
    inputs:
      clusters:
        description: JSON cluster array
        type: string
        required: true
        default: '["api", "bal", "lba", "tdb", "contrat", "recette"]'

jobs:
  setup:
    strategy:
      fail-fast: false
      matrix:
        cluster: ${{ fromJSON(inputs.clusters) }}
    name: Cluster Update ${{ matrix.cluster }}
    uses: "./.github/workflows/update_cluster.yml"
    with:
      cluster: ${{ matrix.cluster }}
    secrets:
      DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      DEPLOY_PASS: ${{ secrets.DEPLOY_PASS }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      VAULT_PWD: ${{ secrets.VAULT_PWD }}
