name: Mise à jour d'un Cluster
on:
  workflow_dispatch:
    inputs:
      cluster:
        type: string
        required: true
      numbers:
        description: JSON environment array
        type: string
        required: true
        default: '[3, 2, 1]'
  workflow_call:
    inputs:
      cluster:
        type: string
        required: true
      numbers:
        type: string
        required: true
    secrets:
      DEPLOY_SSH_PRIVATE_KEY:
        description: SSH private key
        required: true
      DEPLOY_PASS:
        description: SSH PWD TO DEPLOY
        required: true
      SLACK_WEBHOOK:
        description: Slack webhook URL
        required: true
      OPENPGP_PRIVATE_SUBKEY:
        description: Github Actions' OpenPGP private subkey
        required: true
      TOKEN_MNA_SHARED:
        description: Authentication token for accessing private repositories
        required: true

jobs:
  setup:
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        n: ${{ fromJSON(inputs.numbers) }}
    name: Mise à jour de "${{ inputs.cluster }}_${{ matrix.n }}"
    uses: "./.github/workflows/_deploy.yml"
    with:
      environment: "${{ inputs.cluster }}_${{ matrix.n }}"
    secrets:
      DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      DEPLOY_PASS: ${{ secrets.DEPLOY_PASS }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      OPENPGP_PRIVATE_SUBKEY: ${{ secrets.OPENPGP_PRIVATE_SUBKEY }}
      TOKEN_MNA_SHARED: ${{ secrets.TOKEN_MNA_SHARED }}
